@baseUrl = http://localhost:3000

### Get home page
GET {{baseUrl}}/api/notes

### Post note
POST {{baseUrl}}/api/notes
Content-Type: application/json

{
    "title": "Second title",
    "body": "Second body"
}
